application: hostmetric
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /fonts
  static_dir: fonts
- url: /favicon.png
  static_files: img/favicon.png
  upload: img/favicon.png

- url: /.*
  script: main.application  

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

inbound_services:
- mail
